### ISSUE TITLE
When logged out, `user_info()` doesn't have an email attribute

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-GithubFeedbackForm#23]
Is currently broken on production. Quick fix is to just do a `hasattr`

<details><summary>Full details inside</summary>

```log
AttributeError: 

AttributeError: 'TheUser' object has no attribute 'email'
In field index number 6

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 7978, in assemble
    exec_with_trap(question, user_dict)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9329, in exec_with_trap
    exec(the_question.compute, the_dict)
  File "", line 1, in 
NameError: name 'intro' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 6090, in ask
    defaults[field.number] = eval(from_safeid(field.saveas), user_dict)
  File "", line 1, in 
NameError: name 'panel_email' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 6093, in ask
    defaults[field.number] = user_dict['_internal']['dirty'][substitute_vars(from_safeid(field.saveas), self.is_generic, the_x, iterators)]
KeyError: 'panel_email'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/webapp/server.py", line 8058, in index
    interview.assemble(user_dict, interview_status, old_user_dict, force_question=special_question)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8259, in assemble
    raise the_error
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8046, in assemble
    question_result = self.askfor(missingVariable, user_dict, old_user_dict, interview_status, seeking=interview_status.seeking, follow_mc=follow_mc, seeking_question=seeking_question)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8744, in askfor
    return question.ask(user_dict, old_user_dict, the_x, iterators, missing_var, origMissingVariable)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 6097, in ask
    defaults[field.number] = field.default.text(user_dict).strip()
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 1503, in text
    return self.template.render(**the_user_dict)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/mako/template.py", line 451, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/mako/runtime.py", line 828, in _render
    _render_context(template, callable_, context, *args,
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "memory:0x7fb6d11ce950", line 23, in render_body
AttributeError: 'TheUser' object has no attribute 'email'

The referer URL was https://apps.suffolklitlab.org/run/209a/

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 7978, in assemble
    exec_with_trap(question, user_dict)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9329, in exec_with_trap
    exec(the_question.compute, the_dict)
  File "", line 1, in 
NameError: name 'intro' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 6090, in ask
    defaults[field.number] = eval(from_safeid(field.saveas), user_dict)
  File "", line 1, in 
NameError: name 'panel_email' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 6093, in ask
    defaults[field.number] = user_dict['_internal']['dirty'][substitute_vars(from_safeid(field.saveas), self.is_generic, the_x, iterators)]
KeyError: 'panel_email'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/webapp/server.py", line 8058, in index
    interview.assemble(user_dict, interview_status, old_user_dict, force_question=special_question)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8259, in assemble
    raise the_error
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8046, in assemble
    question_result = self.askfor(missingVariable, user_dict, old_user_dict, interview_status, seeking=interview_status.seeking, follow_mc=follow_mc, seeking_question=seeking_question)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8744, in askfor
    return question.ask(user_dict, old_user_dict, the_x, iterators, missing_var, origMissingVariable)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 6097, in ask
    defaults[field.number] = field.default.text(user_dict).strip()
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 1503, in text
    return self.template.render(**the_user_dict)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/mako/template.py", line 451, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/mako/runtime.py", line 828, in _render
    _render_context(template, callable_, context, *args,
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "memory:0x7fb6d11ce950", line 23, in render_body
AttributeError: 'TheUser' object has no attribute 'email'

The external hostname was apps.suffolklitlab.org
```

</details>

**Comment by BryceStevenWilley** [comment]
Unfortunately, this is happening even when the field itself asking for the email is turned off, I guess because DA evaluates the mako templating of the question before the code is evaluated. No other way to fix other than the `hasattr`
